name = "TechnicalIndicatorCharts"
uuid = "ffc6123f-ba44-4b2f-a8ce-46f3306b22af"
authors = ["contributors"]
version = "0.6.8"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LightweightCharts = "d6998af1-87ca-4e7f-83d4-864c79a249fa"
NanoDates = "46f1a544-deae-4307-8689-c12aa3c955c6"
OnlineTechnicalIndicators = "dc2d07fb-478f-4566-8417-81bb3e5a7af1"
TidyTest = "ef104744-fcb3-4e7e-8bb2-6e95860d81ed"

[compat]
Chain = "1"
DataFrames = "1"
DataStructures = "0.19"
DocStringExtensions = "0.9"
LightweightCharts = "2, 3"
NanoDates = "0.3, 1"
OnlineTechnicalIndicators = "0.1"
TidyTest = "0.1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
