name = "TechnicalIndicatorCharts"
uuid = "ffc6123f-ba44-4b2f-a8ce-46f3306b22af"
authors = ["contributors"]
version = "1.0.0-DEV"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LightweightCharts = "d6998af1-87ca-4e7f-83d4-864c79a249fa"
NanoDates = "46f1a544-deae-4307-8689-c12aa3c955c6"
OnlineTechnicalIndicators = "dc2d07fb-478f-4566-8417-81bb3e5a7af1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
